#!/bin/bash

autoload -Uz compinit; compinit

source $HOME/dev_scripts/utils

alias ..='cd ..'
alias ...='cd ../..'

alias ls='ls --color'
alias sortGrep="sed 's/^[^ ]* //' | sort"

if doesCommandExist nvim
then
  alias vi='nvim'
  alias svi='sudo nvim'
  alias vgit='nvim -c :0G'
  alias arc='nvim ~/dev_scripts/aliases'
  alias trc='nvim ~/.config/kitty/kitty.conf'
  alias zrc='nvim ~/.zshrc'
fi

if doesCommandExist lazygit
then
  alias lg='lazygit'
fi

if doesCommandExist lazydocker
then
  alias ld='lazydocker'
  alias initmongo6=$'docker run --hostname 127.0.0.1 -d -p 27017:27017 --name vista_mongo mongo:6.0.19 --replSet vista --logappend; sleep 2 && docker cp $HOME/dev_scripts/mongoInit.js vista_mongo:mongoInit.js && docker exec vista_mongo mongosh mongoInit.js'
  alias initmongo5=$'docker run --hostname 127.0.0.1 -d -p 27017:27017 --name vista_mongo mongo:5.0.17 --replSet vista --logappend; sleep 2 && docker cp $HOME/dev_scripts/mongoInit.js vista_mongo:mongoInit.js && docker exec vista_mongo mongosh mongoInit.js'
fi

if doesCommandExist edit_current_line
then
  autoload -Uz edit-command-line
  zle -N edit-command-line
  bindkey '^e' edit-command-line
fi

if doesCommandExist stow
then
  alias dotfiles='stow --target="$HOME" --dir="$HOME/projects/dotfiles"'
fi

if doesCommandExist git
then
  alias gc='git clone'
  alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
fi

if doesCommandExist orb
then
  source ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi

if doesCommandExist op
then
  source <(op completion zsh)
fi

if doesCommandExist kubectl
then
  source <(kubectl completion zsh)
fi

if doesCommandExist atuin
then
  eval "$(atuin init zsh)"
fi

if doesCommandExist tmux
then
  alias ts='tmux a || tmux new-session -s workspace'
  alias curl-atlnz='curl --socks5-hostname localhost:1080' # work bind
fi


if doesCommandExist fzf
then
  eval $(fzf --$(basename $SHELL))
fi

# Slow to load, lazyload on mise setup
if doesCommandExist mise
then
  mise() {
    unset -f mise
    eval "$($(which mise) activate zsh)"
    mise "$@"
  }
fi
