#!/bin/bash

source $HOME/dev_scripts/utils

alias ..='cd ..'
alias ...='cd ../..'

alias ls='ls --color'

# Neovim + Coding
if doesCommandExist nvim
then
  alias vi='nvim'
  alias svi='sudo nvim'
  alias vgit='nvim -c :0G'
  alias arc='nvim ~/dev_scripts/aliases'
  alias trc='nvim ~/.config/kitty/kitty.conf'
  alias zrc='nvim ~/.zshrc'
fi

if doesCommandExist lazygit
then
  alias lg='lazygit'
fi

if doesCommandExist lazydocker
then
  alias ld='lazydocker'
fi

if doesCommandExist edit_current_line
then
  autoload -Uz edit-command-line
  zle -N edit-command-line
  bindkey '^e' edit-command-line
fi

if doesCommandExist stow
then
  alias dotfiles='stow --target="$HOME" --dir="$HOME/projects/dotfiles"'
fi

if doesCommandExist git
then
  alias gc='git clone'
  alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
fi

if doesCommandExist tmux
then
  alias ts='tmux a || tmux new-session -s workspace'
  alias curl-atlnz='curl --socks5-hostname localhost:1080' # work bind
fi


if doesCommandExist fzf
then
  eval $(fzf --$(basename $SHELL))
fi

if doesCommandExist atuin
then
  eval "$(atuin init zsh)"
fi
