#!/bin/bash

function doesCommandExist() {
  command -v "$1" &> /dev/null
}

function brew() {
  if doesCommandExist brew
  then
    command brew "$@"
    if [[ $* =~ "upgrade" ]] || [[ $* =~ "update" ]] || [[ $* =~ "outdated" ]]; then
      sketchybar --trigger brew_update
    fi
  fi
}

function tunnel-forwarding() {
  if [[ -n "$1" && -n "$2" ]]; then
    ssh -L ${2}:localhost:${2} ${1}
  else
    echo "Usage: tunnel-forwarding <ssh-host> <port-to-forward>"
  fi
}

function watch() {
  if [[ -n "$1" && -n "$2" ]]; then
    npx nodemon --exec $1 $2
  elif [[ -n "$1" ]]; then
    npx nodemon $1
  else
    echo "Usage:"
    echo "\t watch <program-file-path>"
    echo "\t watch <language> <program-file-path>"
    echo ""
    echo "Parameters:"
    echo "\t language:  Provide the language binary, If the language is not specified it will default to 'node'"
    echo "\t program-file-path:  The path of the file/directory to run"
  fi
}

function edit_current_line() {
    local line
    zle -R "Edit current line: "
    read -e -i "$BUFFER" line
    echo "$line" | $EDITOR
    zle accept-line
}
