#!/bin/bash

function doesCommandExist() {
  command -v "$1" &> /dev/null
}

# Lazyload aliases to utilities with some bootstrap
function lazyload() {
  local command="$1"
  shift # left shift on function args
  local bootstrap="$*"
  eval "$command() {
    unset -f $command
    $bootstrap
    $command \"\$@\"
  }"
}

function brew() {
  if doesCommandExist brew
  then
    command brew "$@"
    if [[ $* =~ "upgrade" ]] || [[ $* =~ "update" ]] || [[ $* =~ "outdated" ]]; then
      sketchybar --trigger brew_update
    fi
  fi
}

function tunnel-forwarding() {
  if [[ -n "$1" && -n "$2" ]]; then
    ssh -L ${2}:localhost:${2} ${1}
  else
    echo "Usage: tunnel-forwarding <ssh-host> <port-to-forward>"
  fi
}

function edit_current_line() {
    local line
    zle -R "Edit current line: "
    read -e -i "$BUFFER" line
    echo "$line" | $EDITOR
    zle accept-line
}
