## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
##
## --------------------------------------------------

font=FiraCode Nerd Font Mono:size=8
#font-bold=FiraCode Nerd Font Mono:size=10
#font-italic=FiraCode Nerd Font Mono:size=10
#font-bold-italic=FiraCode Nerd Font Mono:size=10
dpi-aware=auto
