export SSH_AUTH_SOCK=$HOME/.1password/agent.sock
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$(brew --prefix)/bin:$PATH"
export LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH"
export PATH="$(brew --prefix)/opt/llvm/bin:$PATH"
