#!/bin/bash
export gruvInactive=32302f
export gruvActive=62554A

export options=(
	style=square
	active_color=0xff$gruvActive
	inactive_color=0xff$gruvInactive
	ax_focus=on
	hidpi=on
	order=above
	width=8.0
)

borders "${options[@]}"
